
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));
const TranscriptionStatus = lazy(() => import("./pages/TranscriptionStatus.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/signup", element: <UserGuard><Signup /></UserGuard>},
	{ path: "/transcription-status", element: <UserGuard><TranscriptionStatus /></UserGuard>},
	{ path: "/transcriptionstatus", element: <UserGuard><TranscriptionStatus /></UserGuard>},

];
